# Generated by Django 5.2.4 on 2025-07-22 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('storage_limit_gb', models.FloatField()),
                ('max_upload_mb', models.FloatField(default=10.0)),
                ('support_level', models.CharField(choices=[('none', 'No Support'), ('basic', 'Basic Support'), ('priority', 'Priority Support')], default='none', max_length=20)),
                ('sharing_level', models.CharField(choices=[('none', 'No Sharing'), ('read_only', 'Limited Sharing'), ('secure', 'Advanced Sharing')], default='none', max_length=20)),
                ('retention_enabled', models.BooleanField(default=False)),
                ('max_employees', models.IntegerField(blank=True, null=True)),
                ('max_departments', models.IntegerField(blank=True, null=True)),
                ('analytics_level', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('advanced', 'Advanced')], default='none', max_length=20)),
                ('versioning_enabled', models.BooleanField(default=False)),
                ('audit_logs_enabled', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.package')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
