# Generated by Django 5.2.4 on 2025-07-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_active',
        ),
    ]
