# Generated by Django 5.2.4 on 2025-07-21 12:05

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[documents.models.validate_file_extension]),
        ),
    ]
