# Generated by Django 5.2.4 on 2025-07-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='status',
        ),
    ]
