# Generated by Django 5.2.4 on 2025-07-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employeeprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
